# default
spring:
  config:
    import: optional:file:.env[.properties]

  # database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    # 커넥션 풀 설정
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: MYSQL_DB

  # JPA 설정
  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: false
    hibernate:
      jdbc:
        time-zone: Asia/Seoul
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
        default_batch_fetch_size: 1000

  # flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true

  # redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

# P6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true