spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/mukvengers?serverTimezone=UTC
    username: root
    password: team-kkini

  redis:
    host: localhost
    port: 6379

  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect

  flyway:
    enabled: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

jwt:
  expiry-seconds:
    access-token: 5

front:
  server: "https://kkini.vercel.app"

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace