spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mukvengers?serverTimezone=Asia/Seoul
    username: root
    password: team-kkini

  redis:
    host: localhost
    port: 63790

  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect

  flyway:
    enabled: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  slack:
    webhook: ${SLACK_WEBHOOK}

jwt:
  expiry-seconds:
    access-token: 5

front:
  server: "https://kkini.vercel.app"

decorator:
  datasource:
    p6spy:
      enable-logging: true